# Generated by Django 2.0.7 on 2018-08-05 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('CID', models.AutoField(primary_key=True, serialize=False)),
                ('Character_Name', models.CharField(max_length=200)),
                ('Character_Image', models.CharField(blank=True, max_length=200, null=True)),
                ('MIND_stat', models.IntegerField(default=0)),
                ('FIST_stat', models.IntegerField(default=0)),
                ('EYES_stat', models.IntegerField(default=0)),
                ('FACE_stat', models.IntegerField(default=0)),
                ('HEART_stat', models.IntegerField(default=0)),
                ('MaxActionSurges_stat', models.IntegerField(default=0)),
                ('TotalActionSurges_stat', models.IntegerField(default=0)),
                ('ActionSurges_stat', models.IntegerField(default=0)),
                ('Weakness_failed_stat', models.IntegerField(default=0)),
                ('Weakness_passed_stat', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('Group_name', models.CharField(max_length=200)),
                ('GID', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_name', models.CharField(max_length=200)),
                ('PID', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='War_Crime',
            fields=[
                ('War_Crime_ID', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('Group_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Character_HP',
            fields=[
                ('CID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stats.Character')),
                ('MAX_Head_HP', models.IntegerField(default=25)),
                ('Max_Core_HP', models.IntegerField(default=50)),
                ('Max_Right_Arm_HP', models.IntegerField(default=30)),
                ('Max_Left_Arm_HP', models.IntegerField(default=30)),
                ('Max_Right_Leg_HP', models.IntegerField(default=30)),
                ('Max_Left_Leg_HP', models.IntegerField(default=30)),
                ('Head_HP', models.IntegerField(default=0)),
                ('Core_HP', models.IntegerField(default=0)),
                ('Right_Arm_HP', models.IntegerField(default=0)),
                ('Left_Arm_HP', models.IntegerField(default=0)),
                ('Right_Leg_HP', models.IntegerField(default=0)),
                ('Left_Leg_HP', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='GID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Group'),
        ),
        migrations.AddField(
            model_name='character',
            name='PID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Player'),
        ),
    ]
