# Generated by Django 2.0.7 on 2018-08-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20180805_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character_hp',
            name='Head_HP',
            field=models.IntegerField(default=25),
        ),
    ]
