# Generated by Django 2.0.7 on 2018-08-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20180805_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character_hp',
            name='Core_HP',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='character_hp',
            name='Left_Arm_HP',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='character_hp',
            name='Left_Leg_HP',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='character_hp',
            name='Right_Arm_HP',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='character_hp',
            name='Right_Leg_HP',
            field=models.IntegerField(default=30),
        ),
    ]
