# Generated by Django 2.0.7 on 2018-08-06 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20180805_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='war_crime',
            old_name='Group_ID',
            new_name='GID',
        ),
    ]
