# Generated by Django 2.0.7 on 2018-08-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20180805_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='war_crime',
            name='War_Crime_Name',
            field=models.CharField(default='ware', max_length=200),
            preserve_default=False,
        ),
    ]
